services:
  uc:
    image: godatadriven/unity-catalog:0.2.0
    ports:
      - 8080:8080
    volumes:
      - shared-data:/app/unitycatalog
  jupyter:
    user: root
    build:
      dockerfile: Dockerfile.jupyter
    environment:
      JUPYTER_TOKEN: junity
      HOME: /home/junity
      NB_USER: junity
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
      UC_HOST_URL: 'http://localhost:8081/api/2.1/unity-catalog'
      UC_TOKEN: 'test'
    ports:
      - 8888:8888
    depends_on:
      - uc
    volumes:
      - shared-data:/app/unitycatalog
  nginx: # (reverse proxy) Enables service on localhost running outside docker compose network to access UC Catalog API
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
    depends_on:
      - uc

volumes:
  shared-data: